name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure kubectl
        uses: azure/kubectl@v1
        with:
          azcliversion: 'latest'
          kubectl_version: 'latest'
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_CLI_ARGS: "-input=false"
          TF_CLI_CONFIG_FILE: ${{ github.workspace }}/.terraformrc
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

