name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy AWS infrastructure'
        required: true

jobs:
  destroy_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials
          chmod 600 ~/.aws/credentials

      - name: Create script file
        run: |
          echo 'aws eks delete-nodegroup --cluster-name cluster-terraform --nodegroup-name my-nodegroup-terraform &' > destroy_infra.sh
          echo 'sleep 300s' >> destroy_infra.sh
          echo 'aws eks delete-cluster --name cluster-terraform &' >> destroy_infra.sh
          echo 'sleep 300s' >> destroy_infra.sh
          echo 'aws ec2 delete-security-group --group-name api-fiap-sg &' >> destroy_infra.sh
          echo 'sleep 10s' >> destroy_infra.sh
          chmod +x destroy_infra.sh

      - name: Run script
        run: ./destroy_infra.sh
