name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy AWS infrastructure'
        required: true

jobs:
  destroy_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials
          chmod 600 ~/.aws/credentials

      - name: Delete Node Group
        run: |
          aws eks delete-nodegroup --cluster-name cluster-terraform --nodegroup-name my-nodegroup-terraform &
          sleep 300s
          
      - name: Delete Cluster
        run: |
          aws eks delete-cluster --name cluster-terraform &
          sleep 300s

      - name: Delete Security Group
        run: |
          aws ec2 delete-security-group --group-name api-fiap-sg &
          sleep 10s
